services:
  odmpy-ng:
    image: odmpy-ng:dev
    shm_size: 2gb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST_UID: ${HOST_UID:-1000}
      HOST_GID: ${HOST_GID:-1000}
      AUDIOBOOK_FOLDER: ${AUDIOBOOK_FOLDER:-./downloads}
      AUDIOBOOK_TMP: ${AUDIOBOOK_TMP:-./tmp-downloads}
    volumes:
      - ./config:/config
      - ${AUDIOBOOK_FOLDER}:/downloads
      - ${AUDIOBOOK_TMP}:/tmp-downloads
      - ./:/app:ro
    entrypoint: ["/entrypoint.sh"]
    command: []
    restart: no
